# Generated by Django 6.0.2 on 2026-03-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('qr_code', 'QR Code'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='qr_code', max_length=20),
        ),
    ]
