# Generated by Django 6.0.2 on 2026-03-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
