# Generated by Django 6.0.2 on 2026-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/'),
        ),
    ]
