# Generated by Django 6.0.2 on 2026-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteeropportunity_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
