# Generated by Django 6.0.2 on 2026-03-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteeropportunity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteeropportunity')),
            ],
        ),
    ]
