# Generated by Django 6.0.2 on 2026-03-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteerregistration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='volunteerregistration',
            table='volunteerRegisteration',
        ),
    ]
